name: "Test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-16.04
    name: Build test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: scripts/run-test.sh
